config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get 'todos/new', as: 'new_todo'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  patch 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, except: %i[index new create list]
  def index
    @todos = Todo.order(:id)
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    if todo.save
      redirect_to root_path, notice: 'To-do saved.'
    else
      redirect_to new_todo_path, alert: 'An error has occurred, please try again.'
    end
  end

  def show; end

  def edit; end

  def update
    if @todo.update(todo_params)
      redirect_to root_path, notice: 'To-do updated.'
    else
      redirect_to edit_todo_path(@todo), alert: 'Something went wrong, please try again.'
    end
  end

  def destroy
    @todo.destroy
    redirect_to root_path, notice: 'To-do deleted.'
  end

  def complete
    @todo.completed = true
    @todo.save
  end

  def list
    @completed_todos = Todo.where(completed: true)
    @not_completed_todos = Todo.where(completed: false)
  end

  private

  def todo_params
    params.require(:todo).permit(:description)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'Index', root_path, class: 'nav-item nav-link' %>
          <%= link_to 'List', todos_list_path, class: 'nav-item nav-link' %>
          <%= link_to 'New', new_todo_path, class: 'nav-item nav-link' %>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model:@todo, local:true) do |f| %>
  <div class="row form-group">
    <div class="col-md-2 col-form-label">
      <%= f.label :description %>
    </div>
    <div class="col-md-8">
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="col-md-2">
      <%= f.submit 'Submit!', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit To Do</h1>

<% if alert.present? %>
  <div class="alert">
    <p><%= alert %></p>
  </div>
<% end %>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Index</h1>

<% if notice.present? %>
  <div class="notice">
    <p><%= notice %></p>
  </div>
<% end %>

<ul class="list-group">
  <% @todos.each do |todo| %>
    <li class="list-group-item d-md-flex justify-content-between">
      <p><%= todo.description %></p>
      <div class="buttons">
        <%= link_to 'Show', todo_path(todo), class:'btn btn-info' %>
        <%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-secondary' %>
        <%= link_to 'Delete', todo_path(todo), method: :delete, data: {confirm: 'Are you sure?'}, class:'btn btn-danger' %>
        <%= link_to 'Completed?', complete_todo_path(todo), method: :patch, class: 'btn btn-success' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/todos/list.html.erb
<h1>To Do list</h1>

<div class="list-box">
  <div class="row">
    <div class="col-md-6">
      <h2>Incomplete</h2>
      <ul class="list-group">
        <% @not_completed_todos.each do |todo| %>
          <li class="list-group-item">
            <%= todo.description %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-6">
      <h2>Complete</h2>
      <ul class="list-group">
        <% @completed_todos.each do |todo| %>
          <li class="list-group-item">
            <%= todo.description %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<h1>New To Do</h1>

<% if alert.present? %>
  <div class="alert">
    <p><%= alert %></p>
  </div>
<% end %>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1>To Do detail</h1>
<div class="todo-detail">
  <div class="row">
    <div class="col-md-3">
      <h2>Description:</h2>
    </div>
    <div class="col-md-9">
      <p><%= @todo.description %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>Completed:</h2>
    </div>
    <div class="col-md-9">
      <p><%= @todo.completed %></p>
    </div>
  </div>
</div>